---
title: TallTechGuy
email: you@example.com
description: >-
  Personal website for TallTechGuy

baseurl: ""
url: "https://talltechguy.github.io"

# Use the minimal Jekyll theme
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0

# Markdown processor
markdown: kramdown

# Exclude these files from the build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
